# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000
  servlet:
    context-path: /

spring:
  profiles:
    include: activiti
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5 # 去除thymeleaf的严格校验，需要搭配nekohtml依赖一起使用
    cache: false
